extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'

root: true

env:
  node: true
  es6: true
  browser: true

ignorePatterns:
  - 'node_modules/'
  - 'dist/'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project:
    - './tsconfig.json'
    - './build/tsconfig.json'

plugins:
  - '@typescript-eslint'
  - 'import'
  - 'prettier'

rules:
  # Handled by Prettier
  no-extra-semi: off

overrides:
  - files: '**/*.ts'
    rules:
      '@typescript-eslint/triple-slash-reference': off
